## -*- Makefile -*-
##
## 用户: gwguokeqiang
## 时间: 2017-8-23 14:16:43
## Makefile created by Oracle Developer Studio.
##
## 此文件是自动生成的。
##


#### 由所有构建目标共享的编译器和工具定义 #####
CC = gcc
BASICOPTS = -g
CFLAGS = $(BASICOPTS)


# 定义目标目录。
TARGETDIR_main.c=GNU-amd64-Windows


all: $(TARGETDIR_main.c)/main.c

## 目标: main.c
OBJS_main.c =  \
	$(TARGETDIR_main.c)/fig10_02.o \
	$(TARGETDIR_main.c)/fig10_03.o \
	$(TARGETDIR_main.c)/fig10_05.o \
	$(TARGETDIR_main.c)/fig10_07.o \
	$(TARGETDIR_main.c)/fig10_09.o \
	$(TARGETDIR_main.c)/fig10_13.o \
	$(TARGETDIR_main.c)/fig10_16.o \
	$(TARGETDIR_main.c)/fig10_18.o \
	$(TARGETDIR_main.c)/main.o
USERLIBS_main.c = $(SYSLIBS_main.c) 
DEPLIBS_main.c =  
LDLIBS_main.c = $(USERLIBS_main.c)


# 链接或归档
$(TARGETDIR_main.c)/main.c: $(TARGETDIR_main.c) $(OBJS_main.c) $(DEPLIBS_main.c)
	$(LINK.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ $(OBJS_main.c) $(LDLIBS_main.c)


# 将源文件编译为 .o 文件
$(TARGETDIR_main.c)/fig10_02.o: $(TARGETDIR_main.c) fig10_02.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_02.c

$(TARGETDIR_main.c)/fig10_03.o: $(TARGETDIR_main.c) fig10_03.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_03.c

$(TARGETDIR_main.c)/fig10_05.o: $(TARGETDIR_main.c) fig10_05.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_05.c

$(TARGETDIR_main.c)/fig10_07.o: $(TARGETDIR_main.c) fig10_07.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_07.c

$(TARGETDIR_main.c)/fig10_09.o: $(TARGETDIR_main.c) fig10_09.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_09.c

$(TARGETDIR_main.c)/fig10_13.o: $(TARGETDIR_main.c) fig10_13.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_13.c

$(TARGETDIR_main.c)/fig10_16.o: $(TARGETDIR_main.c) fig10_16.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_16.c

$(TARGETDIR_main.c)/fig10_18.o: $(TARGETDIR_main.c) fig10_18.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ fig10_18.c

$(TARGETDIR_main.c)/main.o: $(TARGETDIR_main.c) main.c
	$(COMPILE.c) $(CFLAGS_main.c) $(CPPFLAGS_main.c) -o $@ main.c



#### 清理目标将会删除所有生成的文件 ####
clean:
	rm -f \
		$(TARGETDIR_main.c)/main.c \
		$(TARGETDIR_main.c)/fig10_02.o \
		$(TARGETDIR_main.c)/fig10_03.o \
		$(TARGETDIR_main.c)/fig10_05.o \
		$(TARGETDIR_main.c)/fig10_07.o \
		$(TARGETDIR_main.c)/fig10_09.o \
		$(TARGETDIR_main.c)/fig10_13.o \
		$(TARGETDIR_main.c)/fig10_16.o \
		$(TARGETDIR_main.c)/fig10_18.o \
		$(TARGETDIR_main.c)/main.o
	rm -f -r $(TARGETDIR_main.c)


# 创建目标目录 (如果需要)
$(TARGETDIR_main.c):
	mkdir -p $(TARGETDIR_main.c)


# 启用依赖关系检查
.KEEP_STATE:
.KEEP_STATE_FILE:.make.state.GNU-amd64-Windows

